spring:
  application:
    name: api-gateway

  cloud:
    loadbalancer:
      ribbon:
        enabled: false  # Desabilita o Ribbon, já que estamos usando Spring Cloud Load Balancer
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  config:
    import: "optional:configserver:http://localhost:8888"

server:
  port: 8080

# Configuração do Eureka Client
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:
        http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
